### ISSUE TITLE
Unable to disambiguate emphasis delimiter

### ISSUE THREAD

**Issue by pcj** [atlassian/commonmark-java#10]
AST nodes do not provide start or end indices into the source and `Emphasis.java` and `StrongEmphasis.java` do not provide delimiter infomation.  Therefore, for the input:

```markdown
Hello *Italic* **Bold** _Emph_ __Strong__ ~~Strike~~!
```

It does not currently seem possible to parse this, build an AST, and emit the same markdown back out, as the metadata about the delimiter character is lost.

**Comment by robinst** [comment]
It would be cool to have a CommonMark renderer (cmark has one too)! There's probably more issues related to that, so I've created #12 to track these.

Would you be interested in contributing to this? This issue for example should be pretty simple to implement. Basically put the delimiter char on the node types (see `EmphasisDelimiterProcessor`).

(Excuse my not being responsive by the way, I'm currently on holidays.)

**Comment by pcj** [comment]
I thought that `opener.getLiteral().charAt(0)` would be sufficient in `EmphasisDelimiterProcessor`.  Sometimes the opener literal is null however.  Surprised me.

**Comment by robinst** [comment]
Yeah, that's a bit surprising. The reason is that the opener and closer nodes are truncated before calling the processor in `InlineParserImpl`. Maybe it would make sense to do this after calling the processor.

In this case though, you can call `getDelimiterChar()` in `EmphasisDelimiterProcessor` to get the character.

**Comment by robinst** [comment]
Fixed with #36.

**Comment by robinst** [comment]
Released in 0.5.0.
