### ISSUE TITLE
API changes report for Commonmark Java

### ISSUE THREAD

**Issue by lvc** [atlassian/commonmark-java#107]
The review of API changes for the Commonmark Java library since 0.1.0 version: https://abi-laboratory.pro/java/tracker/timeline/commonmark/

Hope it will be helpful for users and maintainers of the library. The report is generated by the https://github.com/lvc/japi-tracker tool for jars found at http://central.maven.org/maven2/com/atlassian/commonmark/commonmark/.

Thank you.

![commonmark-2](https://user-images.githubusercontent.com/1517837/31065419-c8f2a6ba-a74d-11e7-9855-9967921daee9.png)
![commonmark-1](https://user-images.githubusercontent.com/1517837/31065420-c8f3d026-a74d-11e7-9216-d0d10681fc09.png)

**Comment by robinst** [comment]
That's cool, thanks :). Just in case anyone is looking at this: We're not aiming for a stable API yet (with 0.x), because the CommonMark spec itself is not stable yet.
