### ISSUE TITLE
Leading and trailing spaces are trimmed

### ISSUE THREAD

**Issue by Saketme** [atlassian/commonmark-java#108]
Hello, I'm noticing a strange problem where leading and trailing spaces are getting trimmed from the input. Is there a way to preserve them?

**Comment by Saketme** [comment]
Update: I just realized that multiple spaces and newlines in between text are also ignored. I'm implementing a custom renderer and I'm having trouble figuring out how to not skip those empty characters.

**Comment by robinst** [comment]
Hey. Do you have an example input for your problem? In general, that's kind of what Markup languages do, they don't preserve all the original formatting, especially when it comes to whitespace.

**Comment by Saketme** [comment]
Yep, here is one:

```
private static final String MARKDOWN_TEXT = "The last space in this line gets skipped \n"
      + "And the three new line characters in this line get replaced by a single paragraph node\n\n\n"
      + " The first and last empty characters in this line get skipped. \n"
      + "And the space between two new line characters get skipped in this line\n \n";
```

I understand that you might not want to preserve the original formatting, but I wish this control was given to the renderer instead. 

I will tell you more about my use case. I'm working on a reply screen in my app, where I want to detect markdown syntax in the user editable field in realtime. I'm able to detect nodes using commonmark and highlight them with color, but the difference in the original formatting and commonmark's formatting is proving to be a hurdle. 

I'm currently trying to go through the Parser's code and understand why empty characters are getting skipped. Even if you don't plan to add support for this to the library, would you please point me to the correct place where I can make this modification in a separate fork?

**Comment by robinst** [comment]
Thanks for the example. So this is intentional and according to the CommonMark spec, see "soft line breaks": http://spec.commonmark.org/0.28/#soft-line-breaks

Or try it out here: http://spec.commonmark.org/dingus/?text=one%20%0Atwo%0A%0A%0A%0Athree

The logic for this is in the `parseNewline` method here: https://github.com/atlassian/commonmark-java/blob/master/commonmark/src/main/java/org/commonmark/internal/InlineParserImpl.java#L366
