### ISSUE TITLE
Unable to disambiguate list-item type

### ISSUE THREAD

**Issue by pcj** [atlassian/commonmark-java#11]
Similar to #10, list-item types are lost.

``` markdown
* Item 1
* Item 2
- Dash 1
- Dash 2
```

No information in the AST what the list item type was.  Prevents round-trip parsing/emitting of markdown documents.   

Could be solved by annotating AST nodes with start/end source positions.  Not clear to me how to go about doing that.

**Comment by robinst** [comment]
On `BulletList`, there's `getBulletMarker`, which should return `*` or `-`. Is that not enough? For source positions, see #1.
