### ISSUE TITLE
Delimiter processor conflict with delimiter char ' '

### ISSUE THREAD

**Issue by k0shk0sh** [atlassian/commonmark-java#111]
Steps to reproduce the problem (provide example input):

Two DelimiterProcessor that has two different `opening char` & same `closing char`

Expected behavior:

Renders correctly without throwing an exception 

Actual behavior:

`throw new IllegalArgumentException("Delimiter processor conflict with delimiter char '" + delimiterChar + "'");` in `addDelimiterProcessorForChar(...)`

Is it possible that we can have two Delimiter that has two opening char which are different and similar closing char? 

my use case would be `@mention` & `#issueNumber` both of the `Delimiter` has a closing char as space. 

further example

```
public class MentionDelimiterProcessor implements DelimiterProcessor {

    @Override public char getOpeningCharacter() {
        return '@';
    }

    @Override public char getClosingCharacter() {
        return ' ';
    }

    @Override public int getMinLength() {
        return 1;
    }

    @Override public int getDelimiterUse(DelimiterRun opener, DelimiterRun closer) {
        if (opener.length() >= 1 && closer.length() >= 1) {
            return 1;
        } else {
            return 0;
        }
    }

    @Override public void process(Text opener, Text closer, int delimiterCount) {
        Mention mention = new Mention();
        Node tmp = opener.getNext();
        if (tmp != null) {
            mention.setUrl(((Text) tmp).getLiteral());
        }
        while (tmp != null && tmp != closer) {
            Node next = tmp.getNext();
            mention.appendChild(tmp);
            tmp = next;
        }
        opener.insertAfter(mention);
    }
}
```

```
public class HashTagDelimiterProcessor implements DelimiterProcessor {

    @Override public char getOpeningCharacter() {
        return '#';
    }

    @Override public char getClosingCharacter() {
        return ' ';
    }

    @Override public int getMinLength() {
        return 1;
    }

    @Override public int getDelimiterUse(DelimiterRun opener, DelimiterRun closer) {
        if (opener.length() >= 1 && closer.length() >= 1) {
            return 1;
        } else {
            return 0;
        }
    }

    @Override public void process(Text opener, Text closer, int delimiterCount) {
        HashTag hashTag = new HashTag();
        Node tmp = opener.getNext();
        if (tmp != null) {
            hashTag.setUrl(((Text) tmp).getLiteral());
        }
        while (tmp != null && tmp != closer) {
            Node next = tmp.getNext();
            hashTag.appendChild(tmp);
            tmp = next;
        }
        opener.insertAfter(hashTag);
    }
}
```

**Comment by robinst** [comment]
Hey. Hmm, I'm not sure a delimiter processor is the best approach here. The normal use for them is for syntax that has a balanced pair of marker characters, e.g. `*foo*` or `{bar}`. It also automatically removes those characters, which would not be what you want for the space. I guess you could add it back, but that seems more like a hack.

I would recommend recognizing those two things as a post-processor, similar to how autolinking works. You basically get all the `Text` nodes after inline parsing and you try to find `@mention` & `#issueNumber`.

**Comment by k0shk0sh** [comment]
Is there any reason why closing can't be duplicated? i'm wondering because looking at the autoLink might be overkill for my simple use case.

**Comment by robinst** [comment]
Yes, they are used for finding the right delimiter processor to use. I'm sorry, delimiter processors are not the right tool for this. I just created #113 for a different issue, but it would probably also make your use case simpler, see there.
