### ISSUE TITLE
Please publish a release with Automatic-Module-Name entries

### ISSUE THREAD

**Issue by io7m** [atlassian/commonmark-java#114]
Steps to reproduce the problem (provide example input):

Try compiling any JDK 9 project that wants to use `commonmark-java`: Warnings will be produced by most tools about depending on a filename-based automatic module name.

Expected behavior:

The project publishes `Automatic-Module-Name` entries so that projects can have a stable name upon which to depend.

Actual behavior:

The project defaults to filename-based automatic module names.

**Comment by robinst** [comment]
Thanks, that was on my todo list anyway :). I prepared a pull request. The actual release will be in the new year, as I'm about to go on holidays.

**Comment by robinst** [comment]
Done and released in 0.11.0: https://github.com/atlassian/commonmark-java/blob/master/CHANGELOG.md#0110---2018-01-17

(Also done for the autolink-java dependency in 0.8.0: https://github.com/robinst/autolink-java/blob/master/CHANGELOG.md#080---2018-01-10)

**Comment by io7m** [comment]
Thanks for doing this! Didn't get a chance to thank you before (the notification that this ticket was closed got lost in all the other GitHub noise).
