### ISSUE TITLE
Rendering back to Markdown

### ISSUE THREAD

**Issue by moaxcp** [atlassian/commonmark-java#120]
Steps to reproduce the problem (provide example input):

I have attempted edit Markdown and then render the Mardown. I ran into trouble because there doesn't seem to be a renderer for Markdown. Overall what I'm trying to do is convert Jekyll Markdown posts to JBake asciidoc posts. Asciidoc does not like having multiple level 1 headings and I would like to convert them in Markdown first. This is an example for my use case:

Given a Markdown String

```
# Heading 1

text text text

## Heading 2

text text text

# Heading2

text text text
```
Change all heading levels to +1 and render.

```
## Heading 1

text text text

### Heading 2

text text text

## Heading2

text text text
```

It is possible to visit all headings and set the level to level + 1. But I'm having trouble getting Markdown back out of the document.

```groovy
    document.accept(new AbstractVisitor() {
        void visit(Heading heading) {
            heading.level += 1
            visitChildren(heading)
        }
    })

    println TextContentRenderer.builder().build().render(document)
```

This is when I realized the text renderer doesn't render has Markdown. I also have an example where I need to unlink the front matter yaml header after getting the data out.

```groovy
    def visitor = new AbstractVisitor() {
        YamlFrontMatterVisitor yamlVisitor = new YamlFrontMatterVisitor()
        void visit(CustomNode node) {
            yamlVisitor.visit(node)
            if(node.class == YamlFrontMatterNode) {
                node.unlink()
            }
            visitChildren(node)
        }
        Map<String, List<String>> getData() {
            return yamlVisitor.data
        }
    }
    document.accept(visitor)
```

Expected behavior:

Render changes back to Markdown.

I'm not suggesting that TextContentRenderer should change but It would be nice to have a MarkdownRenderer. Maybe someone knows of a different solution.

Actual behavior:

N/A

**Comment by robinst** [comment]
Hey! Thanks for the detailed issue. This is already tracked in #12 (not sure if you checked the existing issues?). I'm closing this in favor of the other one.

**Comment by moaxcp** [comment]
Sounds great to me! Thanks!
