### ISSUE TITLE
Problem parsing simple mark-down file using

### ISSUE THREAD

**Issue by aptem-k** [atlassian/commonmark-java#121]
**Steps to reproduce the problem (provide example input):**
When parsing a simple file containing just "# abc", the result is corrupted. While parsing same text as a string works fine.

`try (Writer output = new BufferedWriter(new FileWriter("output.html"));
		Reader input = new BufferedReader(new FileReader("input.md"))) {			
	Parser parser = Parser.builder().build();
	Node document = parser.parseReader(input);
	HtmlRenderer renderer = HtmlRenderer.builder().build();
	renderer.render(document, output);			
}`

**Expected behavior:**
`<h1>abc</h1>`

**Actual behavior:**
`﻿# abc</p>`

**Comment by aptem-k** [comment]
I found the root cause of the failure.
My input file contained BOM (“EF BB BF”), once removed it - it worked fine. Still, it would be nice if parser could ignore it.

**Comment by robinst** [comment]
Thanks for raising this. The [spec](http://spec.commonmark.org/) doesn't mention anything about BOMs, and I don't think commonmark-java is the right place to handle this (and I think the rare usage of BOMs is getting increasingly rare as time goes on).

What you can do instead is wrap your input stream in a [BOMInputStream](https://commons.apache.org/proper/commons-io/javadocs/api-2.5/org/apache/commons/io/input/BOMInputStream.html).

I've extended the documentation of `parseReader` a bit to mention BOM, in case others run into this.
