### ISSUE TITLE
ParsertTest.ioReaderTest() depends system settings, leads to failure

### ISSUE THREAD

**Issue by xzel23** [atlassian/commonmark-java#127]
Steps to reproduce the problem (provide example input):
 - clone the commonmark repository on a machine with a platform dependent standard charset that is not UTF-8. Note that the default charset used by `InputStreamReader` [depends on different settings](https://dzone.com/articles/java-may-use-utf-8-as-its-default-charset) and so this may not be reproducible without effort. The test passed on my Mac (english locale) and failed on Windows 7 (english version with german locale).

 - compile and run tests

Expected behavior:
 - tests should pass

Actual behavior:
 - Failure in ParserTest
    ````
    org.commonmark.test.ParserTest > ioReaderTest FAILED
        org.junit.ComparisonFailure at ParserTest.java:45
    
    1357 tests completed, 1 failed, 1 skipped
    ````

**Cause/Fix:** `ParserTest.ioReaderTest()` creates an `InputStreamReader` that uses platform standard encoding and compares to results obtained when using UTF-8 charset (in `TestResources.readAsString(URL)`):

````
    @Test
    public void ioReaderTest() throws IOException {
        ...
        try (InputStreamReader reader = new InputStreamReader(input1)) {
````

should be (requires Java 7, or use `Charset.forName("UTF-8")` as in `TestResources.java`):
````
    @Test
    public void ioReaderTest() throws IOException {
        ...
        try (InputStreamReader reader = new InputStreamReader(input1, StandardCharsets.UTF_8)) {
````

**Caveat:** this happened while I was working on my own fork where I am working towards solving #125, not on master. However I only changed build files so far and this is quite obvious.

**Comment by robinst** [comment]
Thanks, fixed!
