### ISSUE TITLE
Does commonmark-java provide OSGi support?

### ISSUE THREAD

**Issue by ieugen** [atlassian/commonmark-java#128]
Hello,

I would like to use commonmark-java to render markdown content inside an Apache Sling application. 
Does this library provide OSGi support? If not, are you considering it?

Eugen

**Comment by robinst** [comment]
It's been some time since I've used OSGi. I'm pretty sure it works in an OSGi context, but not sure if that's what you mean.

Why don't you go ahead and try it, and report back if there are any problems?
