### ISSUE TITLE
HTML img tag parsed as HtmlBlock node

### ISSUE THREAD

**Issue by noties** [atlassian/commonmark-java#133]
## Steps to reproduce the problem (provide example input):
```markdown
Sample image:

<img src="https://upload.wikimedia.org/wikipedia/en/f/f4/Unrealtournament.jpg" />
```

## Expected behavior:
Given the input above parsed Node structure should be:
```
Document{
  Paragraph{}
  HtmlInline{}
}
```

## Actual behavior:
But instead it is:
```
Document{
  Paragraph{}
  HtmlBlock{}
}
```

I'm redirecting the issue from Markwon repository: [#52](https://github.com/noties/Markwon/issues/52)

**Comment by robinst** [comment]
commonmark-java is consistent with commonmark.js on this, check out the AST tab here: https://spec.commonmark.org/dingus/?text=Sample%20image%3A%0A%0A%3Cimg%20src%3D%22https%3A%2F%2Fupload.wikimedia.org%2Fwikipedia%2Fen%2Ff%2Ff4%2FUnrealtournament.jpg%22%20%2F%3E

In the spec, see bullet number 7 here: https://spec.commonmark.org/0.28/#html-block

Why did you expect it to be inline HTML?

(Also, btw first issue I've seen coming from the Markwon project, hi! 👋😄)

**Comment by noties** [comment]
Hey! I think I have misunderstood the difference between HtmlInline and HtmlBlock (I thought they are applicable to _different_ html entities). Thanks for clarification and for this great library! 🙌
