### ISSUE TITLE
I want to render code how to write (code highlights), I have seen for a long time or no idea.

### ISSUE THREAD

**Issue by qiudaozhang** [atlassian/commonmark-java#138]
Steps to reproduce the problem (provide example input):
render the code like java

Expected behavior:
hightlights

Actual behavior:
no hightlights

**Comment by noties** [comment]
Hey, 

I have a simplified clone of [PrismJs](https://github.com/PrismJS/prism/) for Java: [prism4j](https://github.com/noties/Prism4j). It's not sophisticated and doesn't have theming built-in, but it will allow you to _tokenize_ a supported syntax and apply styling for your needs. I use it in my [Markwon](https://github.com/noties/Markwon) library (`syntax-highlight` module) to provide syntax highlighting to Android applications. 

PrismJs is RegEx based so do not expect something too precise, but it does help with general highlighting. If you have any questions you can create an issue there and I will try to answer it.

**Comment by robinst** [comment]
@qiudaozhang I'm not exactly sure what you want. But if it's syntax highlighting, see @noties pointers.

commonmark-java provides the functionality to provide custom rendering of code blocks, so you'd want to use that together with a syntax highlighting library.

Providing syntax highlighting in commonmark-java itself is not in the scope of this project.

**Comment by qiudaozhang** [comment]
thanks  , i use js have resolve it.

**Comment by molekola-io** [comment]
Hi @qiudaozhang how did you fixed with js? 
Client side on browser?

**Comment by AnzhiZhang** [comment]
You may have a look for [highlight.js](https://github.com/highlightjs/highlight.js) or some java libs
