### ISSUE TITLE
How to implement an inline parser extension

### ISSUE THREAD

**Issue by IlyaGulya** [atlassian/commonmark-java#139]
Hello!
I'm trying to implement parsing of  [Special GitLab References](https://docs.gitlab.com/ee/user/markdown.html#special-gitlab-references)
Specifically those ones, where only starting delimiter exists: `~bug ~"Multiple word fea"`
How can i do this?
I've already tried `DelimiterProcessor` but it seems not to support such cases.
Also, i've tried to implement custom `BlockParser` but it looks like it's consuming the whole line and does not give default parsers ability to do their work.
Seems that it is because of this code inside `DocumentParser`:
```
while (tryBlockStarts) {
...
tryBlockStarts = newBlockParser.isContainer();
```
Does it mean that i can not use `BlockParser` for this purpose?
Is there any way to implement `InlineParser` extension?

As I can see, currently library gives me two ways:

1. Implement own `InlineParser`. This way seems like a overengineering and too hard for such small feature.
2. Do not extend parsing at all and iterate over AST to find `Text` nodes and replace necessary parts with custom nodes. This way seems a bit hacky.

**Comment by robinst** [comment]
Hey! Yeah so the best way currently is to do option 2. That's what the autolink extension in this repository does too, so you can have a look at its code to see how it does it.

There's an open issue for making inline parsing extensible, see #113.

Let me know if you need any help!
