### ISSUE TITLE
Table formatting not working

### ISSUE THREAD

**Issue by FracturedRetina** [atlassian/commonmark-java#142]
Steps to reproduce the problem (provide example input):

```
||Alveolar|Bilabial
|:--|:-:|:-:
|**Plosive**|t, d|b
|**Tap**|ɾ|
```

Expected behavior:

||Alveolar|Bilabial
|:--|:-:|:-:
|**Plosive**|t, d|b
|**Tap**|ɾ|

Actual behavior:

||Alveolar|Bilabial|:--|:-:|:-:|**Plosive**|t, d|b|**Tap**|ɾ|

**Comment by robinst** [comment]
Are you using the `commonmark-ext-gfm-tables` artifact as described here?:

https://github.com/atlassian/commonmark-java#extensions

**Comment by FracturedRetina** [comment]
Yes, other tables work in the same document, just not this one.

**Comment by FracturedRetina** [comment]
It works when the number of dashes is >= 3

**Comment by robinst** [comment]
I copied the table from your description and pushed a test for it, which works: https://github.com/atlassian/commonmark-java/commit/941578f4aff1dbaa7265c791d6b92a16a7236c1b

Can you include the source for the table that you are trying that doesn't work?

**Comment by robinst** [comment]
Closing this. There might be some differences to how GitHub does tables. We should check against the spec, see #84.

**Comment by robinst** [comment]
FYI the tables extension has been updated to match the GitHub spec in the newest release (0.13.0).

@FracturedRetina can you check if that fixes your issue?
