### ISSUE TITLE
Eclipse error for Parser.builder().build()

### ISSUE THREAD

**Issue by axkr** [atlassian/commonmark-java#144]
In version 0.12.1 for the following line:

```
    Parser parser = Parser.builder().build();
```

the Eclipse compiler returns a error:

**The type org.commonmark.parser.Parser$Builder cannot be resolved. It is indirectly referenced from required .class files** 

In version 0.11.0 there is no such problem with that line.
Probably because `Parser.Builder` is private in version 0.12.1?

**Comment by robinst** [comment]
Thanks for reporting this. This is weird, because the class is not private in 0.12.1 (there was no change there): https://github.com/atlassian/commonmark-java/blob/commonmark-parent-0.12.1/commonmark/src/main/java/org/commonmark/parser/Parser.java#L125

Do you have a small(ish) project that I can use to reproduce?

**Comment by axkr** [comment]
This is the outline which Eclipse show for version 0.12.1.
In version 0.12.1 the Builder is private?
The JAR has 223.860 Bytes in my Maven
![grafik](https://user-images.githubusercontent.com/3109793/49565818-cdb50200-f928-11e8-87f0-3a18ee30aa11.png)

This is the outline which Eclipse show for version 0.12.1. Downloaded from:
https://mvnrepository.com/artifact/com.atlassian.commonmark/commonmark/0.12.1
The JAR has 134.291 Bytes
![grafik](https://user-images.githubusercontent.com/3109793/49566428-dc041d80-f92a-11e8-90c5-13231e7288e1.png)

**Comment by axkr** [comment]
Wierd? But it seems to work now.

Thanks for your help.

**Comment by robinst** [comment]
Spooky :). No worries!
