### ISSUE TITLE
How can I render * as html bold text?

### ISSUE THREAD

**Issue by baole** [atlassian/commonmark-java#147]
Is there anyway to convert *some text* into HTML <strong>some text</strong>?

**Comment by robinst** [comment]
Do you mean parsing CommonMark, then converting italic (emphasis) to bold (strong emphasis), and then rendering as HTML?

If so, yes that's possible. After parsing, you can use a visitor to go over all the nodes and replace Emphasis nodes with StrongEmphasis.

**Comment by robinst** [comment]
Yeah. There's an example of using a visitor in the readme. For replacing the node, you'll need to create a new StrongEmphasis node and then attach all the original child nodes of Emphasis to it, and then remove the Emphasis.

**Comment by baole** [comment]
Thank you so much for your help @robinst. I tried to follow example in README

Here is my example Markdown text:
`"This is *bold* and _italic_ text"`

I expected to generate an HTML like this:
`<p>This is <b>bold</b> and <i>italic</i> text</p>`

However, Parser considers both *bold* and _italic_ as Emphasis. I probably need to customize Parser and some twists in HtmlRenderer.  How can I parse different delimiter to different node type, in this case, '*' becomes StrongEmphasis and "_" becomes Emphasis?

**Comment by baole** [comment]
Here is my solution using reflexion to replace default AsteriskDelimiterProcessor
https://gist.github.com/baole/8cada2ca3e55fa42e6ea59b905b8a21b

**Comment by robinst** [comment]
I'm on mobile right now, but it's probably easier to walk the nodes and check the delimiter using the methods on Emphasis, see docs: https://static.javadoc.io/com.atlassian.commonmark/commonmark/0.12.1/org/commonmark/node/Emphasis.html#getOpeningDelimiter--

**Comment by baole** [comment]
The main issue is `UnderscoreDelimiterProcessor` (process "_" and "__") and `EmphasisDelimiterProcessor` (process "*" and "**") uses the same implementation and generate Emphasis node for "_" or "*" and StrongEmphasis  node for "__" or "**" and I'm not sure how to overwrite EmphasisDelimiterProcessor to generate StrongEmphasis for "*"
