### ISSUE TITLE
Escape pipe in code section of table leaves escape character

### ISSUE THREAD

**Issue by jawscout** [atlassian/commonmark-java#149]
Escaping a pipe in the code section of a table keeps the escape character when the spec shows that it shouldn't.

Steps to reproduce the problem (provide example input):
``` Markdown
| f\|oo  |
| ------ |
| b `\|` az |
| b **\|** im |
```

Expected behavior:
``` HTML
<table>
<thead>
<tr>
<th>f|oo</th>
</tr>
</thead>
<tbody>
<tr>
<td>b <code>|</code> az</td>
</tr>
<tr>
<td>b <strong>|</strong> im</td>
</tr></tbody></table>
```

Actual behavior:
``` HTML
<table>
<thead>
<tr><th>f|oo</th></tr>
</thead>
<tbody>
<tr><td>b <code>\|</code> az</td></tr>
<tr><td>b <strong>|</strong> im</td></tr>
</tbody>
</table>
```
Links:
https://github.github.com/gfm/#example-193

**Comment by robinst** [comment]
Hey, thanks for the good bug report! There's an open issue about checking our extension against the spec (the spec didn't exist when the extension was originally written), I guess this is one of the issues.

I'm currently on holiday but will take a look when I'm back. If you feel like it, have a look at the code, it should not be too difficult to fix :).

**Comment by ViceIce** [comment]
Any news? This is a really annoying bug.

**Comment by robinst** [comment]
Working on this on a new branch: https://github.com/atlassian/commonmark-java/compare/issue-149-gfm-table-spec-changes?expand=1

**Comment by robinst** [comment]
Merged, will be in the next release (0.13.0).

**Comment by ViceIce** [comment]
Any estimate for the next release?

**Comment by robinst** [comment]
Now 😄

https://github.com/atlassian/commonmark-java/blob/master/CHANGELOG.md#0130---2019-07-15
