### ISSUE TITLE
Using A Visitor

### ISSUE THREAD

**Issue by silenuz** [atlassian/commonmark-java#15]
in your visitor example:

~~~
Node node = parser.parse("...");
MyVisitor visitor = new MyVisitor();
node.accept(visitor);

class MyVisitor extends AbstractVisitor {
    @Override
    public void visit(Paragraph paragraph) {
        // Do something with paragraph (override other methods for other nodes):
        System.out.println(paragraph);
        // Descend into children:
        visitChildren(paragraph);
    }
}
~~~

What should be printed to System out?  Because I tried on a few things and when visiting both headers and paragraphs all it prints is the type folowed by curly braces like this:

~~~
INFO: Visit:(p)- Paragraph{}
~~~

I thought maybe it would print out the contents of the node?  How do I get to the content of the node?

**Comment by pcj** [comment]
Paragraph nodes are not terminal nodes, they typically contain children that ultimately lead to terminals, like code and text elements.  Descend down the tree as you are doing with `visitChildren` and override `visit(Text)` and get the string literal from there:

~~~java
        @Override
        public void visit(org.commonmark.node.Text node) {
            System.out.println(node.getLiteral());
        }

~~~

**Comment by robinst** [comment]
Thanks @pcj, that's right. Maybe we should change the example to something more meaningful. Maybe visiting all links and printing the destination? Any other ideas?

**Comment by silenuz** [comment]
Okay thanks.  I had seen Issue #8 and thought that maybe CommonMark might work the same as Pegdown where you can get the content of the node as a string.  I was hoping to use Commonmark's AST to do syntax hi-lighting as Pegdown has so many dependencies and I prefer CommonMark's renderer.

**Comment by pcj** [comment]
@robinst Word counting examples are pretty standard in the text mining / classification domains.  Could update the example to count words in a Markdown document.

**Comment by robinst** [comment]
Good idea, changed the example now: https://github.com/atlassian/commonmark-java#use-a-visitor-to-process-parsed-nodes
