### ISSUE TITLE
Newlines inside triple backtick rendered as html

### ISSUE THREAD

**Issue by sporritt** [atlassian/commonmark-java#151]
Steps to reproduce the problem (provide example input):

Parse a string representing a code block delimited by triple backticks:

<pre>
```\nthis code\n\nshould not have BRs or paragraphs in it\nok\n```
</pre>

Expected behavior:

```
<pre><code>
this code

should not have BRs or paragraphs in it
ok

</code></pre>
```

Actual behavior:

```
<pre><code>this code<br><br>should not have BRs or paragraphs in it<br>ok<br></code></pre>
```

**Comment by robinst** [comment]
It doesn't render as `<br>`, see the test case I just added: https://github.com/atlassian/commonmark-java/commit/7b80b7fabe94554d2a85e8fa13472e1f18f15939

(Closing this until you can provide a reproducible problem.)

**Comment by sporritt** [comment]
yes, you're right, it turns out our code had an extra line that converted the output of the renderer:

```
markdownRenderer.render(document).replaceAll("(?<!\\>)\\n", "<br>")
```

which appears to be someone's response to how Markdown treats newline characters:

https://daringfireball.net/projects/markdown/syntax#p

ie. that you don't get a `<br>` unless you leave two blank spaces before the newline.  

In our use case - supporting comments by a wide range of users, not necessarily tech people - this is not intuitive (in fact I'd argue that it's not intuitive for _anybody_, but that's not your problem, i know). When they press enter in a comment they expect it to result in a newline, for instance as in this test:

```
render("this\nis text\non 3 lines") must equalTo("<p>this<br>is text<br>on 3 lines</p>\n")
``` 

For the benefit of anyone who happens across this issue in the future, in our case the solution was to set the "softbreak" on the builder:

```
val markdownRenderer = HtmlRenderer.builder().softbreak("<br />").build()
```

which is much nicer than the extra regex replace we had before.

Having said all that, though, @robinst, I see the test you created does not test that the leading `\n` is honoured:

```
assertRendering("```\nthis code\n\nshould not have BRs or paragraphs in it\nok\n```",
                "<pre><code>this code\n" +
                        "\n" +
                        "should not have BRs or paragraphs in it\n" +
                        "ok\n" +
                        "</code></pre>\n");
```

And I can confirm in our own tests that it is not honoured if present.  This can have a bearing on the output:

![image](https://user-images.githubusercontent.com/262720/55162717-4c47e080-5160-11e9-963e-c48e80c99336.png)
