### ISSUE TITLE
Newline character needed to parse correctly the next markdown line of code

### ISSUE THREAD

**Issue by Daniel-NZ** [atlassian/commonmark-java#153]
**Steps to reproduce the problem (provide example input):**

I use all extensions provided by the pacakage and i noticed that a missing newline character (\n) cannot let the markdown engine parser succeed in parsing the next markdown line of code. 

Between TEST and the first |, there is one newline character and it failed to detect the | as an HTML table. If you insert TWO newline characters, the | character is recognized correctly.
```
String source2 = 
"TEST" +
"\n" +
"| Plugin | README |\n" +
"| ------: | ------ |\n" +
"| Dropbox | [plugins/dropbox/README.md][PlDb] |\n" +
"| Github | [plugins/github/README.md][PlGh] |\n" +
" [PlDb]: <https://github.com/joemccann/dillinger/tree/master/plugins/dropbox/README.md>\n" +
"   [PlGh]: <https://github.com/joemccann/dillinger/tree/master/plugins/github/README.md>\n";
```
It seems that this behavior prevents the markdown parsing to work correctly in other cases.

**Expected behavior:**

An HTML table must be created.

**Actual behavior:**

Failure to create the HTML table.

**Comment by Daniel-NZ** [comment]
Other cases with these lines of code : 

```
String source = "@WebMethod" +
"\n" +
"    String readCookie( @CookieParam(\"MyName\") String myName ) throws\n" +
"		Exception\n" +
"    {\n" +
"       return myName;\n" +
"    }" );
```
Between @WebMethod and the word String, there is one newline character and everything in converted into a single p HTML paragraph like this : 

```
<p>@WebMethod
String readCookie( @CookieParam(&quot;MyName&quot;) String myName ) throws
Exception
{
return myName;
}</p>
```
If you put two newline characters just after @WebMethod, you have what is awaited : 
```
<p>@WebMethod</p>
<pre><code>String readCookie( @CookieParam(&quot;MyName&quot;) String myName ) throws
	Exception
{
   return myName;
}
</code></pre>
```

**Comment by robinst** [comment]
The behavior for indented code blocks is consistent with the [CommonMark spec](https://spec.commonmark.org/0.29/#indented-code-blocks):

> An indented code block cannot interrupt a paragraph, so there must be a blank line between a paragraph and a following indented code block.

You can try out an interactive example here: https://spec.commonmark.org/dingus/?text=first%20line%0A%20%20%20%20code%3F

For the table, it's consistent with GitHub's implementation. Try this in a comment:

```
test
foo|bar
---|---
baz|qux
```

You'll see that it's not recognized as a table either.
