### ISSUE TITLE
Escape html with markdown not working

### ISSUE THREAD

**Issue by ruidiasbraga** [atlassian/commonmark-java#154]
I have an implementation of the commonmark, if I place the markdown first, it works, if I place html first, everything is html escaped (because in both cases I have escape html set to true)

Steps to reproduce the problem (provide example input):

`HtmlRenderer htmlRenderer = HtmlRenderer.builder().softbreak("<br />").escapeHtml(true).extensions(extensions).build();`

```
<h1>ddd</h1> 
# markdown
```

Expected behavior:
_(i needed to put on code block, but the idea is to show as text)_

`<h1>ddd</h1> `
# markdown

Actual behavior:
_(i needed to put on code block, but the idea is to show as text)_
`<h1>ddd</h1> # markdown`

if I give a line interval between the two lines everything works.

**Comment by robinst** [comment]
It's not clear to me what you mean. Are you expecting the `# markdown` line to get turned into a heading?

In that case, it needs to be in a separate block (separated from the HTML by newline). This is consistent with the spec and the reference implementation, see this example in the spec: https://spec.commonmark.org/0.29/#example-131
