### ISSUE TITLE
Strikethrough is not parsed properly in a specific edge case

### ISSUE THREAD

**Issue by matdziu** [atlassian/commonmark-java#158]
Steps to reproduce the problem (provide example Markdown if applicable):

```
private val extensions = listOf(StrikethroughExtension.create())
private val parser = Parser.builder().extensions(extensions).build()
private val renderer = HtmlRenderer.builder().extensions(extensions).build()

val output = renderer.render(parser.parse("~~TESTEST~~~~@{{some_uuid}FIRSTNAME, SECONDNAME}~~"))
```

Expected HTML:

`output == "<p><del>TESTEST</del><del>@{{some_uuid}FIRSTNAME, SECONDNAME}</del></p>"`

Actual HTML

`output == "<p><del>TESTEST</del>~~@{{some_uuid}FIRSTNAME, SECONDNAME}~~</p>"`

This is a test snippet from Kotlin codebase (Android app).

**Comment by robinst** [comment]
Hey, thanks for the clear bug report :).

The way strikethrough works is exactly the same as other emphasis, such as `**`. If you [try this in commonmark.js](https://spec.commonmark.org/dingus/?text=**TESTEST****%40%7B%7Bsome_uuid%7DFIRSTNAME%2C%20SECONDNAME%7D**):

```
**TESTEST****@{{some_uuid}FIRSTNAME, SECONDNAME}**
```

The result is:

```
<p><strong>TESTEST</strong>**@{{some_uuid}FIRSTNAME, SECONDNAME}**</p>
```

I would be very hesitant to change this. [GitHub's spec for strikethrough](https://github.github.com/gfm/#strikethrough-extension-) is not very detailed about how it works either, so I wouldn't even know what exactly it should accept or not.
