### ISSUE TITLE
The version in the Jcenter repository is still 11.0 and has not been updated

### ISSUE THREAD

**Issue by XhstormR** [atlassian/commonmark-java#162]
https://jcenter.bintray.com/com/atlassian/commonmark/commonmark/maven-metadata.xml

**Comment by robinst** [comment]
Hey. I never published to bintray (as far as I remember), only to Maven Central. Is it possible to see how the old versions got there?

**Comment by XhstormR** [comment]
Jcenter repository is the default repository when currently developing android applications. I just noticed that the libraries on Jcenter are not up to date. 

I don't know why, maybe it's a mirror, but I don't know why it's not updated.

**Comment by robinst** [comment]
Going to close this. I think the documentation is clear enough and points to Maven Central. I don't want to deploy to multiple repositories.

Maybe we could ask jcenter to remove the old artifacts? Not sure if they do that.
