### ISSUE TITLE
Does TextContentRender support Extensions?

### ISSUE THREAD

**Issue by JemmyWong** [atlassian/commonmark-java#170]
### Steps to reproduce the problem (provide example Markdown if applicable):
I want to strip markdown to plain text.

This is my code:
```
String markdownFilter(String markdown) {
    Renderer textRender = TextContentRenderer.builder()
                .extensions(Arrays.asList(
                    StrikethroughExtension.create(),
                    AutolinkExtension.create(),
                    InsExtension.create(),
                    HeadingAnchorExtension.create())
                ).build();
    
    Parser parser = Parser.builder().build();
    
    String plainText = markdown;
    try {
        plainText = textRender.render(parser.parse(markdown));
    } catch (Exception e) {
        log.error("markdown to plain text failed: " + markdown, e);
    }
    return plainText;
}
```

I tested `~makdown~`, `++markdown++`, `# markdown`.

### Expected behavior:
return `markdown`, `markdown`, `markdown`, separately.

### Actual behavior:
return`~markdown~`, `++markdown++`, `markdown`, separately.

`~markdown~`, `++markdown++` don't change.
`# markdown` stripped to `markdown`.

I noticed these words in [README.md](https://github.com/atlassian/commonmark-java#extensions):
> Extensions need to extend the parser, or the HTML renderer, or both. 

So do extensions support text render? If not, how can I strip strike through and other extensions?

(Also see what the reference implementation does: https://spec.commonmark.org/dingus/)

**Comment by robinst** [comment]
Hey! Yeah most of the extensions do support text rendering. The problem in your example is that you also need to register the extensions with the parser (otherwise the extension syntax is not parsed):

```java
List<Extension> extensions = Arrays.asList(
        StrikethroughExtension.create(),
        AutolinkExtension.create(),
        InsExtension.create(),
        HeadingAnchorExtension.create()
);
Renderer textRender = TextContentRenderer.builder()
        .extensions(extensions)
        .build();
Parser parser = Parser.builder()
        .extensions(extensions)
        .build();

String markdown = "# header\n\n~~strikethrough~~ and ++insert++";
String plainText = textRender.render(parser.parse(markdown));
System.out.println(plainText);

```

So the input:

```
# header

~~strikethrough~~ and ++insert++
```

Returns:

```
header
/strikethrough/ and 
```

Looks like `InsExtension` currently doesn't provide a text node renderer. I can raise a PR for that.

**Comment by JemmyWong** [comment]
Thanks.

**Comment by robinst** [comment]
Done, will be in the 0.15.1 release which should appear in Maven Central in a few hours.
