### ISSUE TITLE
community extension site / reference

### ISSUE THREAD

**Issue by McFoggy** [atlassian/commonmark-java#173]
I would like to know if there is somewhere a list of commonmark-java extensions or if you would mind to publish one in your README ?

I would like to reference one of the extensions I created a while ago : [commonmark-ext-notifications](https://github.com/McFoggy/commonmark-ext-notifications) which allows, like admonitions in Asciidoc, to annotate paragraphs as `INFO`, `SUCCESS`, `WARNING`, `ERROR` via an easy to remember syntax:

```
! This is an info message.
!v This is a success message.
!! Consider this a warning.
!x This is an error message.
```
which can then be rendered as 

![](https://cloud.githubusercontent.com/assets/1119660/14935335/09ada1b0-0ece-11e6-9387-738a4a475923.png)

**Comment by robinst** [comment]
Hey! Cool :).

Yeah, I don't mind adding some references to the readme. Let's add another section `### Third-party extensions` before `See also`. Mind raising a PR for that?

**Comment by McFoggy** [comment]
Sure, I will.
