### ISSUE TITLE
Underscore emphasis not being parsed if nearby characters

### ISSUE THREAD

**Issue by ipsk** [atlassian/commonmark-java#183]
Hello! I have noticed that when using emphasis and strong emphasis with `_` instead of `*` it does not get parsed when near a character.
I tried on http://spec.commonmark.org/dingus/ and it also seems to be the case there.
So I was wondering if this is a bug or an intended feature.

Steps to reproduce the problem (provide example Markdown if applicable):

```
T__esting__
```

Expected behavior:
T**esting**
```
T<strong>esting</strong>
```

Actual behavior:

```
T__esting__
```

It is not the case when using `*`.

**Comment by robinst** [comment]
>  I tried on http://spec.commonmark.org/dingus/ and it also seems to be the case there.
> So I was wondering if this is a bug or an intended feature.

It's intended yeah. The spec goes into more detail here: https://spec.commonmark.org/0.29/#emphasis-and-strong-emphasis
