### ISSUE TITLE
Prevent message trimming

### ISSUE THREAD

**Issue by MarkMarkine** [atlassian/commonmark-java#186]
Hello, I was wondering if it is possible to prevent trimming of first and last white space of the message.
For example:  
` Hello **sir**! ` will turn  into `<p>Hello <strong>sir<strong>!<p>`, the result I wanted would be  `<p> Hello <strong>sir<strong>! <p>`.  
My reasoning is very particular so I would understand if it's not possible, I am currently simply using the Markdown visitor to get the components since I am not rendering it into HTML, which requires me to sometimes split it into different messages, so when joining them together it looses all the spaces it had.  

Ps: If can't be prevented can you please point me to the part of the code that does the trimming of the node? I would love to fork it and change for my use.  
Thank you!

**Comment by robinst** [comment]
Hey. Hm yeah, this is intentional to follow the spec, see [example 192](https://spec.commonmark.org/0.29/#example-192) and 196:

> Leading spaces are skipped

> Final spaces are stripped before inline parsing, so a paragraph that ends with two or more spaces will not end with a hard line break

Hmm, what if you remember the leading and trailing whitespace, strip it, and then after parsing and rendering, add them on again? (Not sure what your output is.)
