### ISSUE TITLE
Invalid html will be rendered using HTML-Blocks

### ISSUE THREAD

**Issue by mueller-jens** [atlassian/commonmark-java#190]
When using the example [118](https://spec.commonmark.org/dingus/?text=%3Ctable%3E%3Ctr%3E%3Ctd%3E%0A%3Cpre%3E%0A**Hello**%2C%0A%0A_world_.%0A%3C%2Fpre%3E%0A%3C%2Ftd%3E%3C%2Ftr%3E%3C%2Ftable%3E%0A) from the spec i get invalid html generated. It is also the case in reference implementation and i have also reported a bug there.

In case i use this example the `</p>` will be rendered with after the `</pre>` what leads to an invalid XHTML, because the order of the opening tags have the opposite order.

Steps to reproduce the problem (provide example Markdown if applicable):

```
<table><tr><td>
<pre>
**Hello**,

_world_.
</pre>
</td></tr></table>
```

Expected behavior:

```
<table><tr><td>
<pre>
**Hello**,
<p><em>world</em>.</p>
</pre>
</td></tr></table>
```

Actual behavior:

```
<table><tr><td>
<pre>
**Hello**,
<p><em>world</em>.
</pre></p>
</td></tr></table>

```

(Also see what the reference implementation does: https://spec.commonmark.org/dingus/)

**Comment by robinst** [comment]
> It is also the case in reference implementation and i have also reported a bug there.

Mind pointing to that issue?

**Comment by mueller-jens** [comment]
@robinst Sorry can't get you. What i would say is that the html is rendered in your library is the same as in the reference implementation but in my  opinion it should render a valid HTML. 
The `<pre></pre>` tags should be inside the `<p></p>` tags or outside

**Comment by robinst** [comment]
Yeah, I got that part. I was asking about this:

> i have also reported a bug there

Can you link to that bug report? I'm interested in the spec discussion.

**Comment by mueller-jens** [comment]
It was not really a discussion: https://github.com/commonmark/commonmark-spec/issues/668

**Comment by robinst** [comment]
Ah I see. Ok, so because we implement the commonmark spec, we won't change our behavior for this either. It might fix your particular problem but might break someone else's formatting.

If the spec changes, we would adapt.
