### ISSUE TITLE
Support for conditional delimiter processing 

### ISSUE THREAD

**Issue by pcj** [atlassian/commonmark-java#22]
Thinking about superscript and subscript: in pandoc, the following is valid `2^10^`, but `^a cat^` is not interpreted as superscript, unless one escapes the space (`^a\ cat^`).  

How would the current delimiter parsing scheme handle this?

**Comment by robinst** [comment]
Hm, good question.

It may be possible to do that special handling in `DelimiterProcessor::process`: check what's between the opener and closer, and if there's an unescaped space in there, put the delimiters back in the text.

That doesn't sound ideal, but I'm pretty sure we shouldn't handle each and every special case by giving special instructions to the inline parser either.

**Comment by robinst** [comment]
Closing this, we can reopen in case the current API doesn't work for this.
