### ISSUE TITLE
Inline delimiter parser can not be registered more than once, delimiter character: ~

### ISSUE THREAD

**Issue by pcj** [atlassian/commonmark-java#23]
Trying to implement a separate extension for subscript like `H~2~0`, but I can't use tilde in conjunction with the existing `ext-gfm-strikethrough` extension, as they clash on parser registration.  A workaround seems to be create a new extension that bundles both, something like `ext-subscript-and-gfm-strikethrough` that works similar to the `EmphasisDelimiterProcessor`. This is somewhat ugly, but perhaps reasonable since this should be a fairly rare occasion. 

Thoughts?

**Comment by robinst** [comment]
I'm not sure if it's a good idea to implement this as a delimiter processor. Have you looked at doing it in a post-processing step on `Text` nodes instead?

I'd also be very interested in how pandoc implemented this.

**Comment by szeiger** [comment]
The current restriction on delimiter characters is rather aggressive. It should be possible to register the same delimiter multiple times if the minimum number of delimiter characters differs. I have implemented this in my patched ParserBuilder here https://github.com/szeiger/ornate/blob/b76669837bf8e4efca558fb8be535227c644dc2c/core/src/main/scala/com/novocode/ornate/commonmark/CustomParserBuilder.scala#L54-L127 for the same reason (using `strikethrough` together with my own `subscript` extension). Preliminary tests indicate that it works as intended.

**Comment by robinst** [comment]
@szeiger Interesting. Can you come up with a way to integrate that into `InlineParserImpl`? A pull request would be much appreciated :).
