### ISSUE TITLE
Can we have a 0.4.1 release?

### ISSUE THREAD

**Issue by eiszfuchs** [atlassian/commonmark-java#39]
I'm currently working on an app that deals with small texts and I figured it would be nice if it had basic CommonMark support.
I included `compile 'com.atlassian.commonmark:commonmark:0.4.0'` to my dependencies and added the Parser, but building and running the code would throw an exception:

```
java.util.regex.PatternSyntaxException: U_ILLEGAL_ARGUMENT_ERROR
^\p{IsWhite_Space}
```

I saw that this issue was fixed (https://github.com/atlassian/commonmark-java/commit/b954f82cb582e619f08fb58345c31a635b31d5f1) *right after the 0.4.0 release*, so a new version soon would be great! :+1:

**Comment by robinst** [comment]
Sure, done :)! Release notes are here: https://github.com/atlassian/commonmark-java/releases/tag/commonmark-parent-0.4.1

The search index on Maven Central hasn't updated yet, but you can already use it as a dependency.

**Comment by eiszfuchs** [comment]
Nice, thank you very much! :beer:

**Comment by robinst** [comment]
Cheers :beer:
