### ISSUE TITLE
Escaping of pipe symbol in gfm-tables-0.4.1 is not supported

### ISSUE THREAD

**Issue by PaulKlint** [atlassian/commonmark-java#45]
GFM tables allow escaping of the pipe symbol in table cells. For example:

| AAA | BBB |
|-------|--------|
| a\|b  |   c    |

This is not supported in gfm-tables-0.4.1.

**Comment by robinst** [comment]
Can you supply a test case for this? There's [one in TablesTest](https://github.com/atlassian/commonmark-java/blob/master/commonmark-ext-gfm-tables/src/test/java/org/commonmark/ext/gfm/tables/TablesTest.java#L160-L170) for escaping pipes.

Rendering your example results in this, which looks correct:

```html
<table>
<thead>
<tr><th>AAA</th><th>BBB</th></tr>
</thead>
<tbody>
<tr><td>a|b</td><td>c</td></tr>
</tbody>
</table>
```
