### ISSUE TITLE
Disable autoconverting HTML entity references

### ISSUE THREAD

**Issue by md384** [atlassian/commonmark-java#50]
As the title says, is there a way to disable autoconverting HTML entity references, e.g. `&alpha;` to `α`? I am saving the converted HTML in a DB which is Windows-1252 encoded (can't be changed right now) so having some problems.

**Comment by robinst** [comment]
What if the input contains `α` already? Just having an option to disable converting HTML entity references wouldn't be enough.

We could add an option to the HTML renderer to encode all non-ASCII characters using numeric character references, but I'd rather not encourage using legacy encodings.

Can you do post-processing on the resulting text instead as described above? You'd have to be careful to handle surrogate pairs correctly, but I can help you with that.

**Comment by md384** [comment]
I used post-processing as you suggested.

**Comment by robinst** [comment]
Cool. Would you mind sharing that piece of code here? Surrogate pairs can be tricky to get right, maybe other people would also be interested in this.

**Comment by md384** [comment]
I didn't deal with surrogate pairs, I just put something together that worked for our use-case. 

That could be useful for others so I'll leave it here but it is basic and hacky and probably won't be enough for most.

```
private static final Pattern sf_htmlEntityPattern = Pattern.compile("&(#[xX][a-fA-F0-9]{1,8}|#[0-9]{1,8}|[a-zA-Z][a-zA-Z0-9]{1,31});");
private static final Pattern sf_escapedHtmlEntityPattern = Pattern.compile("&amp;(#[xX][a-fA-F0-9]{1,8}|#[0-9]{1,8}|[a-zA-Z][a-zA-Z0-9]{1,31});");

/**
   * Escape HTML entities (e.g. &alpha;) as the markdown parser auto-converts to unicode characters.
   * &xxx; escapes to &amp;xxx; then find and replace these using unescapeHtmlEntities.
   *
   * Call escapeHtmlEntities on pre-parsed markdown and unescapeHtmlEntities on renderer html.
   */
private static String escapeHtmlEntities(String text) {
  return sf_htmlEntityPattern.matcher(text).replaceAll("\\\\&$1;");
}

private static String unescapeHtmlEntities(String text) {
  return sf_escapedHtmlEntityPattern.matcher(text).replaceAll("&$1;");
}
```

**Comment by robinst** [comment]
Ah, I see, thanks for sharing. When you're doing it like this, you don't have to handle surrogate pairs, so that's fine.

But if there's already non-ASCII in your input, that won't be escaped. But I guess in your use case you ensure that the input is already ASCII only?

**Comment by kevinmilner** [comment]
@robinst, I would like to voice my opinion that there really should be an option to disable this sort of auto-conversion. I build my own workaround, but think this should be a feature (as is evident by the multiple closed-without-a-fix issues requesting it, like this one). I couldn't use the escaping method mentioned by @md384 (though it did borrow from it) because it was messing up my anchor links, which do need to strip out special characters. Here's what I did:

```
	private static final Pattern htmlEntityPattern = Pattern.compile(
			"&(#[xX][a-fA-F0-9]{1,8}|#[0-9]{1,8}|[a-zA-Z][a-zA-Z0-9]{1,31});");
	
	/**
	 * Converts the given Markdown to HTML and writes to a file
	 * @param markdown
	 * @param outputFile
	 * @throws IOException
	 */
	public static void writeHTML(String markdown, File outputFile) throws IOException {
		List<Extension> extensions = Arrays.asList(TablesExtension.create(), HeadingAnchorExtension.create());
		Parser parser = Parser.builder().extensions(extensions).build();
		Map<String, String> htmlSymbols = new HashMap<>();
		// track any html entities that were explicitly included, so that we can re-escape them after commonmark un-escapes them
		Matcher symbolMatcher = htmlEntityPattern.matcher(markdown);
		while (symbolMatcher.find()) {
			String symbol = symbolMatcher.group();
			if (!htmlSymbols.containsKey(symbol)) {
				String concrete = StringEscapeUtils.unescapeHtml4(symbol);
//				System.out.println(symbol+" => "+concrete);
				htmlSymbols.put(symbol, concrete);
			}
		}
		Node document = parser.parse(markdown);
		HtmlRenderer renderer = HtmlRenderer.builder().extensions(extensions).build();
		
		FileWriter fw = new FileWriter(outputFile);
		String html = renderer.render(document);
		for (String symbol : htmlSymbols.keySet())
			html = html.replaceAll(htmlSymbols.get(symbol), symbol);
		fw.write(html);
		fw.close();
	}
```

**Comment by robinst** [comment]
@kevinmilner What is your reason/use case for that? Would encoding non-ASCII characters as character references work?

**Comment by kevinmilner** [comment]
> @kevinmilner What is your reason/use case for that? Would encoding non-ASCII characters as character references work?

@robinst I've noticed portability problems. Specifically, I generate Markdown programatically with HTML4 symbols, then use commonmark-java to convert it to HTML. A user of my code recently did this on a Mac, then uploaded to the resultant HTML to a linux server and all of the symbols were garbled. Here's the [generated HTML that has garbled greater-than-or-equal-to symbols](http://www.its.caltech.edu/~pagem/RidgecrestDrill/) (see `Mâ‰¥5.0 Hazard Change Over Time` in the table of contents), and [here is the markdown used to generate it](http://www.its.caltech.edu/~pagem/RidgecrestDrill/README.md), which includes text like `M&ge;5.0 Hazard Change Over Time`.

Thanks for the reply and the great package!
