### ISSUE TITLE
is it possible to alter laziness in block quote

### ISSUE THREAD

**Issue by rshah** [atlassian/commonmark-java#53]
Just found the library and tried it to write some extension to support non standard syntax.
In short, i want to use commonmark-java library infrastructure to parse and/or render non standard syntax too. 

Now, i'm trying to implement the blockquote rule but without laziness.
For example:

```
>Quote line1
>Quote line2
This should not be part of quote
```

Using above syntax i expected the result like below(but without extra line between the 'Quote line2' and 'This should not be part of quote'

> Quote line1
> Quote line2

This should not be part of quote

Is it possible to alter the laziness for my blockquote rule?
Which file should i read more?

**Comment by robinst** [comment]
The code handling the lazy paragraph continuation is here: https://github.com/atlassian/commonmark-java/blob/master/commonmark/src/main/java/org/commonmark/internal/DocumentParser.java#L233-L237

But there's currently no way to disable the behavior there. And I'm not sure if it would be a good idea to expose that as an option on the parser, as [the spec](http://spec.commonmark.org/0.25/#block-quotes) doesn't mention that it could be optional.

Having said that, maybe we can have a flag method on `BlockParser` for extensions to control the behavior. Is that what you're asking? It would mean that you'd basically have to have your own copy of `BlockQuoteParser` just to tweak the behavior.

I'm interested in hearing more about your use case though. What other non-standard syntax would you want to support?

**Comment by razie** [comment]
The way I handle extra syntax/markup is to have my own parser in front of the common mark parser. It is slower that way, having to re-parse the entire text, it would be nice if there was a way to add custom rules to the parser, to recognize other non-conflicting syntax and add custom nodes to the AST.

thanks and cheers - awesome library!

**Comment by rshah** [comment]
@robinst 
Yes, as my first attempt, i tried creating extension for `BlockQuote` by copying `BlockQuoteParser` but did not work. And as you pointed out seems not possible now to disable the behavior.
The syntax currently i'm trying to support, use newline to break the continuation from previous line (in most cases). As in the example above. As initial support i also created SoftLineBreak extension to render the newline as `<br />`

So maybe adding flag could help to achieve it.
Another syntax to create the blockquote where newline inside the syntax block is ignored.
```
{quote}
  Quote
  This is a 
  paragraph
{/quote}
```
will be rendered as 
> Quote
> This is a 
> paragraph

Some syntax examples:

Purpose | Syntax | Result
----------- | ---------- | --------
Bold | `''Bold''` | **Bold**
Italic | `'''Italic'''` | _Italic_
Strike | `%%Strike%%` | ~~Strike~~
Header | * H1<br> ** H2 | <h1>H1</h1><br><h2>H2</h2>
BlockQuote | {quote} <br>  Quote<br>  This is a quote<br>{/quote} <br><br> > Quote <br> > This is a quote | Block Quote
URL | http://www.example.com<br>`[[Example>http://www.example.com/]]`<br>`[[Example:http://www.example.com/]]` | www.example.com<br>[Example](url)<br>[Example](url)
Link to an issue,<br> Link to a wiki page | [[BUG-98]],[[WikiPageName]] | [BUG-98](url), [WikiPageName](url)
Unordered list | - Item A<br>- Item B<br>&nbsp; -- Item B.1 | <ul><li>Item A</li><li>Item B</li><ul><li>Item B.1</li></ul></ul>
Ordered list | + Item A<br>+ Item B | <ol><li>Item A</li><li>Item B</li></ol>
Coloring text foreground and background |  ` &color(#f00) { Color }` | foreground red text
 | `&color(red) { Color } ` | foreground red text
 | `&color(#ffffff, #abd500) { Color } ` | foreground white text, green background
Fence code block | {code}<br>package helloworld;<br>public class Hello {<br>&nbsp;&nbsp;public String sayHello() {<br>&nbsp;&nbsp;&nbsp;return "Hello"; <br>&nbsp;&nbsp;}<br>&nbsp;}<br>{/code} | code block
Table ver 1 | \| A \| B \| C \|<br>\|a\|b\|c\| | table
Table ver 2 | \| A \| B \| C \|h<br>\|a\|b\|c\| | rendered as table header(with default background color)
Table ver 3 | \|~No.1\|aaa\|bbb\|<br>\|~No.2\|ccc\|ddd\| | No.1 and No.2 will be rendered with background color 
Link to a Subversion Revision | #rev(revision number)<br>e.g. #rev(11) | [r11](url)
Link to a Git Revision | #rev(repository:revision)<br>e.g. #rev(app:abcdeabcde) | [app:abcdeabcde](url)
Break | ```aaa&br;bbb``` | aaa<br>bbb


For bold, italic and strike, i created extension using custom delimiter processor codes taken from Emphasis as base codes.
Also copied HeadingParser and created extension for Heading syntax.

Thank you for your time.

**Comment by robinst** [comment]
@razie It's already possible to implement custom rules for block level elements by registering block parser factories. But yeah, for inline parsing, it's very limited currently, the only extension mechanism is delimiter processors. I'm also not sure how an API for that would look like yet, and there's gonna be significant changes to the inline parsing to enable source positions for inline elements.

@rshah That seems like a completely different syntax instead of additions. Some of them even conflict with existing syntax, e.g. why is `* H1` a heading and not a bullet list item? I would recommend not basing your parser on commonmark-java in that case. What you could reuse if you wanted to is the node classes and the HTML rendering parts.

**Comment by rshah** [comment]
@robinst 
I'm sorry for late reply.
Isn't it possible by extension mechanism to alter the default parser behavior?
In this case, i will create extension as many as needed to support the syntax in order to reuse this library logic.
I tried changing the lazy paragraph continuation directly in the code, but when compiling all test case failed.
Where is the test specification written? If possible i would like to change the test spec or disable it temporarily.

**Comment by robinst** [comment]
Hey @rshah. I'm sorry I kept this open for so long, but I'm closing this now.

From your table it really sounds like you want a completely different parser, so changing commonmark-java to accommodate doesn't sound like a good fit.

Feel free to reuse individual code though, of course.

(As for the title of this issue, altering laziness might be worth adding an option for, I'm open to a pull request for that part.)
