### ISSUE TITLE
Add underline support

### ISSUE THREAD

**Issue by rjoly** [atlassian/commonmark-java#54]
Hello,

Could we add a ```UnderlineExtension``` in a new artifact ```commonmark-ext-gfm-underline```? It would be a cousin class of the existing ```StrikethroughExtension``` in artifact ```commonmark-ext-gfm-strikethrough```, with few little changes on this new class and others related to.

If you agree this issue, I could submit a pull request. However, I just need to know which delimiter should be the more accurate to do so.
I thing we should use an "easy to use" character on both QWERTY and AZERTY keyboards (and some others?), with a double occurrence. Here are some proposals: ```--``` or ```&&``` or ```%%```.

Thank you in advance for your feedback.

**Comment by robinst** [comment]
Hey :).

Can you point me to an existing Markdown implementation that has support for this? From [this StackExchange question](http://programmers.stackexchange.com/questions/207727/why-there-is-no-markdown-for-underline), it looks like this is not really something that is intended.

I'm also interested in your use case, what do you need this for? And is the HTML support not suitable to do this (e.g. use `<u>foo</u>`)?

**Comment by rjoly** [comment]
I had been reading the same StackExchange question and I understand the answer, only regarding the Markdown philosophy (more or less "meaning versus presentation"). I also notice the underline is not easy to read and should introduce some confusion with the conventional rendering of hyperlinks.

In my use case, I want to allow my final user to easily format a text with understandable code (not HTML code). So I think Markdown can help me to do this easily and efficiently. But the underline feature is one of the favourite features needed by these end users (with the 2 existing levels of emphasis which are traduced by italic and bold presentation) and is not in the Markdown perimeter.

I can't use ```<u>foo</u>``` because my end user will forget the ```/``` to close the tag, or make any other mistake. It would also force me to break the user input escaping of my UI framework to rebuild it with my small arms, just for a ```<u>``` tag.

So, as your implementation offers a strikethrough extension, which doesn't seem to be part of the Markdown specification, I suggest to had an underline extension. As I understand, as an extension, it won't change the default implementation which respects the Markdown specification.
I know the ```<del>``` tag is a semantic one contrary to the ```<u>``` one, but I think it should be a useful feature in some case.

Note: looking for markdown implementation with underline, I found a source talking about the ```<ins>``` tag. This little-used tag mean that its content has been inserted and the default presentation is to underline the text.

**Comment by robinst** [comment]
If `<ins>` would work for you, I think it would be ok to add it as an extension. There's precedence for the `++` syntax as well:

* https://github.com/markdown-it/markdown-it-ins
* https://github.com/aleray/mdx_del_ins

Do you want to contribute this extension? It should be fairly simple, it should work the same way as the strikethrough extension. We could probably call it `commonmark-ext-ins`.

**Comment by rjoly** [comment]
Thank you for ```<ins>``` references you found on other projects. The ```++``` seems to make sense !

I tried to contribute this extension which should be quite simple, but I'm facing an unexpected issue with my development environment (Eclipse) which is not able to build the project. It seems that I can't access the Atlassian repositories to get few dependencies. 

Unfortunately, I don't think I will have enough time during next weeks to solve this problem. If someone could take it in charge, it would be great. If not, I will try to do it when I have some time to do so.

**Comment by robinst** [comment]
> It seems that I can't access the Atlassian repositories to get few dependencies.

Really? All the dependencies are in Maven Central. Can you add the full error message here?

> If not, I will try to do it when I have some time to do so.

Cool, let me know if you have any other problems.

**Comment by robinst** [comment]
@pabranch contributed this, see linked pull request above :). I'm keeping this issue open until it's in a released version.

**Comment by pabranch** [comment]
New PR #61 to add the `InsExtension` to the integration tests. Missed it the first time around, sorry 'bout that.

**Comment by robinst** [comment]
Released 0.7.0 with these changes, thanks @pabranch and @rjoly 🎉: https://github.com/atlassian/commonmark-java/releases/tag/commonmark-parent-0.7.0
