### ISSUE TITLE
Parse backtick quotes (`) failed. 

### ISSUE THREAD

**Issue by yhonet** [atlassian/commonmark-java#57]
I want to start a code block like `<div>`、`<table>`、`<pre>`、`<p>` etc. It is begin and end with a backtick quotes(`).
But it looks like the parser don't understand this. The parser show a backpack quote char and then start a large div block, and the div block don't end until it reached the end of the page.

**Comment by robinst** [comment]
I'm sorry, I'm having trouble understanding the problem. Could you include a complete example and what you expect the output to be?

**Comment by robinst** [comment]
Closing this. If you comment with an example, I can open it.

It also rather sounds like the issue is with the commonmark spec, not this implementation. Please check if [Dingus](http://spec.commonmark.org/dingus/) behaves the same way.
