### ISSUE TITLE
Table rendering is failing

### ISSUE THREAD

**Issue by spyhunter99** [atlassian/commonmark-java#63]
using `commonmark-ext-gfm-tables:0.7.0` with the following input. It actually produces nothing.

````

| Module 	|Javadocs 	|
| ------ 	|-------- 	|
| gradle-fury-validation 	| [Javadocs](javadocs/gradle-fury-validation/index.html) 	|
| hello-gradhell 	| [Javadocs](javadocs/hello-gradhell/index.html) 	|
| hello-universe-lib 	| [Javadocs](javadocs/hello-universe-lib/index.html) 	|
| hello-world-aar 	| [debug](javadocs/hello-world-aar/debug/index.html) 	 |
| hello-world-aar 	| [release](javadocs/hello-world-aar/release/index.html) 	 |
| hello-world-lib 	| [Javadocs](javadocs/hello-world-lib/index.html) 	|
| hello-world-war 	| [Javadocs](javadocs/hello-world-war/index.html) 	|


````

I've tried adding more whitespace, removing the links, removing the leading and trailing pipes. What am I doing wrong?

````
            List<org.commonmark.Extension> extensions = new ArrayList<>();
            extensions.add(org.commonmark.ext.gfm.tables.TablesExtension.create());
            extensions.add(org.commonmark.ext.gfm.strikethrough.StrikethroughExtension.create());
            extensions.add(org.commonmark.ext.autolink.AutolinkExtension.create());
            Parser parser = Parser.builder().extensions(extensions).build();

            Node document = parser.parse(contents);
            HtmlRenderer renderer = HtmlRenderer.builder().build();
            String contents = renderer.render(document);  // document is the content above
````

**Comment by robinst** [comment]
The extensions also need to extend the HTML rendering part. In your code, it looks like you only add them when building the parser. Try creating the `HtmlRenderer` like this:

    HtmlRenderer renderer = HtmlRenderer.builder().extensions(extensions).build();

**Comment by spyhunter99** [comment]
awesome that fixed it! consider adding that to the wiki or readme. I almost wrote off this project. You sir, rock

**Comment by robinst** [comment]
Phew 😅

The example code here shows it: https://github.com/atlassian/commonmark-java#extensions

Any ideas how I can make it stand out more?

**Comment by spyhunter99** [comment]
wow, i don't know how i missed it. I think i started with https://github.com/atlassian/commonmark-java#parse-and-render-to-html and didn't just didn't notice the difference. Thanks for the quick response

**Comment by robinst** [comment]
I've wrapped the lines now, maybe that makes it stand out more: add7fee8fd267a6365d1b08c1a3c01f9c0da716a

**Comment by spyhunter99** [comment]
fantastic, thanks again. I'm using this to build a maven site plugin for gradle. Much appreciated
