### ISSUE TITLE
Table borders

### ISSUE THREAD

**Issue by spyhunter99** [atlassian/commonmark-java#64]
Is there a way to inject a css style into generated tables or to turn on borders? I'd love a bootstrap styled .table kind of thing

**Comment by razie** [comment]
$("table").addClass("table table-striped");

**Comment by spyhunter99** [comment]
success, thanks!

**Comment by robinst** [comment]
Thanks @razie :). You could also use an `AttributeProvider` for this, see the example I just added: https://github.com/atlassian/commonmark-java#add-or-change-attributes-of-html-elements
