### ISSUE TITLE
Github wiki style markdown issue

### ISSUE THREAD

**Issue by spyhunter99** [atlassian/commonmark-java#65]
As an experiment, I took the wiki from http://github.com/osmdroid/osmdroid, cloned it and ran it through the commonmark and ran into a few issues.

1. it appears that relative links to another wiki page isn't resolved...
```
2. Walk through the [tutorial](How-to-use-the-osmdroid-library)
```
The target page is generated but the extension .html is missing. Not sure if there's anything that can be done to work around this.
2. The double bracket syntax isn't appear to be handled at all
```
[[osmdroid thirdparty|osmdroid thirdparty]]
```

If necessary, I can go back and alter all of the wiki pages to use full urls, but as always, I'll look for less painful solution

**Comment by robinst** [comment]
1. Yes. We use the destination of a link as it appears in the source. The library doesn't know how documents relate to each other or that in your particular use case, pages have an additional `.html` at the end.

   You can get the result you want by writing a `Visitor` that looks at all the `Link` nodes and appends an `.html` to the destination if it is a relative link. See [Link.setDestination](https://github.com/atlassian/commonmark-java/blob/master/commonmark/src/main/java/org/commonmark/node/Link.java#L45) and `getDestination`.

2. There's currently no extension to handle that syntax in the parser.

   What you can do to handle this is to have another `Visitor` that looks at `Text` nodes and tries to find `[[`. If it does, it can split the `Text` node into two and insert a `Link` node.

   Let me know how that works for you, and feel free to paste your code here in case you get stuck.

**Comment by spyhunter99** [comment]
1. I think if I follow your pattern and look for links that don't start with http or https or have any protocol for that matter. That should be an indicator that it's a relative link. In my case, I would just append the html extension and be off the races. I'll give it a shot.

2. An easier fix was just remove the double bracket syntax. Turns out it was only on one page. Someone should fire the guy that put it there! (it was me and i don't get paid for this)

**Comment by spyhunter99** [comment]
Update on 1. I wrote the visitor and was able to alter the destination urls rather painlessly, but I noticed that my visitor didn't hit any of the link nodes when there was whitespace within the destination link. Probably something that's easier to fix by fixing the markdown, but i figured this fact was worth sharing with you all. It may be something that can be 'fixed' however it's clearly happening in the parsing phase

**Comment by robinst** [comment]
Good to hear. For others looking at this, appending `.html` was done in a `PostProcessor`, see here: https://github.com/chrisdoyle/gradle-fury/commit/2155f4273e3de7f798017b804849248b833e2b62#diff-03707e81bf9b997cacb37e8e1d38d2b3R240

> I noticed that my visitor didn't hit any of the link nodes when there was whitespace within the destination link

Yes, this works as intended. Spaces are not allowed in link destinations in the CommonMark spec: http://spec.commonmark.org/0.26/#link-destination
