### ISSUE TITLE
commonmark-ext-gfm-tables single column table

### ISSUE THREAD

**Issue by leobuettiker** [atlassian/commonmark-java#7]
Would expect to be able to render a single column table. Following code does not render a table.

        final String input = "| First Header |\n" +
                "| ------------- |\n" +
                "| Content Cell |\n" +
                "| Content Cell |\n";
        List<Extension> extensions = Arrays.asList(TablesExtension.create());
        Parser parser = Parser.builder().extensions(extensions).build();
        Node document = parser.parse(input);
        HtmlRenderer renderer = HtmlRenderer.builder().extensions(extensions).build();
        System.out.println(renderer.render(document));

**Comment by robinst** [comment]
Confirmed, definitely a bug. Looks like this is the minimal syntax for a single column:

```
|Header
---
```

**Comment by leobuettiker** [comment]
Unfortunately the specification of the table is not clear for edge cases https://help.github.com/articles/github-flavored-markdown/#tables

As I read the specification your example would be valid (minimal) tables. So would be an example where the vertical bar would be on the right.

**Comment by robinst** [comment]
Yeah, it doesn't really have a spec :). But you can try the syntax using the Preview in comments here.

What I'm not happy about with the above example is that in CommonMark, it's a setext header. And extensions should try to avoid changing existing block-level syntax. I'm thinking of requiring at least one pipe for the separator line, e.g. these would be tables:

```
|Header
|---
```


```
Header|
---|
```

And your original example as well. Thoughts? I have a patch that implements this, I'll push it soon.

**Comment by robinst** [comment]
Fixed as described above. I'll release this soon.

**Comment by robinst** [comment]
Released in [0.2.0](https://github.com/atlassian/commonmark-java/releases/tag/commonmark-parent-0.2.0).

**Comment by leobuettiker** [comment]
Thanks a lot!
