### ISSUE TITLE
Editing enclosing <pre> tag attributes for an IndentedCodeBlock with AttributeProviderFactory

### ISSUE THREAD

**Issue by PainterAndHacker** [atlassian/commonmark-java#74]
I'm new to `commonmark-java`, and am trying to figure out how to apply a CSS class to all  `<pre>` tags surrounding an `IndentedCodeBlock`. I was successfully able to apply attributes to `Header` and `BlockQuote` nodes, but if I match a Node  with `IndentedCodeBlock` and add a class to the attribute map, then it applies it to the `<code>` tag in the HTML it renders.

I think what's happening here is that `<pre>` isn't a Node, just an artefact of the way the `HtmlRenderer` renders the `IndentedCodeBlock` (and `FencedCodeBlock`) Nodes, and so I'm never able to override the attributes for the `<pre>` tag because it never goes through the `AttributeProviderContext` as a Node. 

If I'm understanding this correctly, the only way to do this would be to override the rendering itself for `FencedCodeBlocks` and `IndentedCodeBlocks`.

Do you think it makes sense to allow for overriding the attributes of tags where more than 1 set of tags is generated per node? Perhaps the `AttributesProvider` could provide attributes for the outer tags first with an override for providing attributes inside of the nested structure?

**Comment by PainterAndHacker** [comment]
Note that editing the CSS on the surrounding pre-block isn't easily doable even if I apply a class attribute to the code block, since I can't [reference the parent based on the child](http://stackoverflow.com/questions/4220327/css-selector-element-with-a-given-child). I'm trying to make it so that the code blocks are coloured differently and don't overflow, but to do that I need to apply a style to the `<pre>` tag.

**Comment by robinst** [comment]
Hey! You found the problem I hoped nobody would notice ;).

I think we can solve this by passing in the tag name that we're adding attributes for. That would mean the AttributeProvider would get called twice, once with `pre` and another time with `code`.

What do you think?

**Comment by PainterAndHacker** [comment]
Do you mean that the renderer would call `setAttributes` for each tag (as opposed to each node), with a signature like `setAttributes(Node node, String tagName, Map<String, String> attributes)`? That could definitely work, although the tag would need the Node context too (which I included in the signature) since the same tag could be generated in different contexts.

Or what about calling it on each node, but with a signature like `setAttributes(Node node, Map <String, Map <String, String>> allAttributes)`, where `allAttributes` is map from the tag name -> the attribute map for that particular tag. That way there is only one call per node, but it's more generic for multiple layers of tags.

(I haven't looked very in depth on how the renderer is actually using the factory, so please correct me if I'm misunderstanding the process.)

**Comment by robinst** [comment]
Yep, I meant calling it multiple times, with an additional string argument.

The `Map<Map<...` seems a bit too complicated and error-prone (what happens when implementation removes a whole tag, or adds new ones, etc).

I plan to look into this tomorrow!

**Comment by robinst** [comment]
Implemented and released in [version 0.8.0](https://github.com/atlassian/commonmark-java/releases/tag/commonmark-parent-0.8.0) now. Thanks for reporting! :)
