### ISSUE TITLE
generating a pdf

### ISSUE THREAD

**Issue by omidp** [atlassian/commonmark-java#75]
Hi,

I'm trying to generate pdf using this project with creating a custom org.commonmark.renderer.Renderer. the problem is, the render method returns String which in my case it has flaw design and is not needed, IMHO, it would be better if it was outputstream or byte[] do you have any suggestion ?

**Comment by robinst** [comment]
Hey! That sounds like a cool project. I'm not sure if I would try to render to PDF directly or go from the HTML instead.

Apart from that, it seems like a PDF renderer should have an entirely separate interface, yeah. Is there a reason why you'd want to use the same interface for this?

**Comment by omidp** [comment]
Actually I need a complex Opentype shaping for RTL languages in pdf and at the moment there is no htmltopdf generator which supports it so I have to generate pdf on my own ,based on markdown that's why a [PDFRenderer](https://github.com/omidp/htmltopdf/blob/master/src/main/java/com/omidbiz/htmltopdf/PdfRenderer.java) is needed.
I created a [project](https://github.com/omidp/htmltopdf/) to implement it.    
You can run the sample code [here](https://github.com/omidp/htmltopdf/blob/master/src/main/java/com/omidbiz/htmltopdf/CommonMarkdownPdfRunner.java)

**Comment by robinst** [comment]
Had a quick look. I would recommend not using `Renderer`, it doesn't gain you anything. Instead, it's probably simpler if you just use a `Visitor` to visit all the nodes and do the rendering.

I'm closing this issue, but let me know if you run into any problems!
