### ISSUE TITLE
TextContent extension for GFM tables

### ISSUE THREAD

**Issue by ahjaworski** [atlassian/commonmark-java#80]
There is an extension for parsing and rendering markdown with GFM tables to HTML, but there is no support for textcontent. 

In my usecase I want to be able to parse and render markdown content with GFM tables to plain text and html. Especially for inline style GFM tables and empty headers, the formatting could be improved by an extension, in my opinion.

This is a possible text output:
<pre>
Markdown | Less | Pretty
--- | --- | ---
*Still* | `renders` | **nicely**
1 | 2 | 3
<pre>

**Comment by robinst** [comment]
Hey! Yeah, would be nice to have a text rendering implementation for tables. Do you want to look into contributing that part? You can have a look at existing implementations in extensions, some pointers:

* https://github.com/atlassian/commonmark-java/blob/master/commonmark-ext-gfm-strikethrough/src/main/java/org/commonmark/ext/gfm/strikethrough/StrikethroughExtension.java#L52-L60
* https://github.com/atlassian/commonmark-java/blob/master/commonmark-ext-gfm-strikethrough/src/main/java/org/commonmark/ext/gfm/strikethrough/internal/StrikethroughTextContentNodeRenderer.java#L7

As for the output, I think inline formatting for things like emphasis and code should be rendered exactly like the existing text content rendering works.

**Comment by ahjaworski** [comment]
I finally managed to get started on this issue and have submitted a pull request. I've implemented a text content renderer that we used in a project for an e-mail template engine. We used this renderer with a Markdown input (with GFM tables), which could render both HTML and plain text e-mails. The output of the text content renderer can be discussed, for now I've implemented a very simple output.

**Comment by ahjaworski** [comment]
Pull request: https://github.com/atlassian/commonmark-java/pull/115

**Comment by robinst** [comment]
Released in 0.11.0 now, thanks @ahjaworski! https://github.com/atlassian/commonmark-java/blob/master/CHANGELOG.md#0110---2018-01-17
