### ISSUE TITLE
Document if the classes are threadsafe.

### ISSUE THREAD

**Issue by DavidBiesack** [atlassian/commonmark-java#83]
Can a Parser or HtmlRenderer be used in a threaded environment - shared across threads?

**Comment by robinst** [comment]
Yes it can! It takes care to use new state for each parse/render call. Although I should probably add tests for that and document it properly.

**Comment by DavidBiesack** [comment]
Thanks, @robinst -- as suggested, please add a note about this in the README. Thanks!

**Comment by robinst** [comment]
Added tests and a section to the README now, thanks for raising this!
