### ISSUE TITLE
Check GFM extensions against new spec

### ISSUE THREAD

**Issue by robinst** [atlassian/commonmark-java#84]
GitHub just posted on their blog that GitHub-flavored Markdown is now CommonMark + extensions and has a spec: https://githubengineering.com/a-formal-spec-for-github-markdown/

Spec lives here: https://github.github.com/gfm/

Check our implementation of tables, strikethrough (and maybe autolinking) against the spec.

**Comment by robinst** [comment]
Did tables as part of #149. Checked others too:

* strikethrough: Not much in spec, no need to test against that :)
* autolinking: Too different from what we have at the moment

So I'm closing this.

**Comment by robinst** [comment]
Released as part of 0.13.0: https://twitter.com/niborst/status/1150946272976621569

**Comment by AfzalivE** [comment]
> autolinking: Too different from what we have at the moment

Any chance this has gotten easier to implement since 2019?
