### ISSUE TITLE
is there an easy way to replace the added <p>  by <div>   ?

### ISSUE THREAD

**Issue by phavelar** [atlassian/commonmark-java#86]
is there an easy way to replace the added `<p>`  by `<div>`   ?

thanks !

**Comment by robinst** [comment]
Yes, you should be able to override node rendering for `Paragraph` nodes. So like the [Customize HTML rendering](https://github.com/atlassian/commonmark-java#customize-html-rendering) example, but using `Paragraph` instead of `IndentedCodeBlock`.

Please try it out and report back if that helps :).

**Comment by phavelar** [comment]
I solved like this:
It's a bit convoluted, my desired outcome is to replace added <p> tags by <div> as well as to remove extra "\n"  appended after each transformation.
If instead we have these as properties, this could be a lot simpler. (no need to override).
thank you for your reply.



    private static class ReplaceDefaultParagraphs extends CoreHtmlNodeRenderer {

        public static final String OPENED_DIV = "div";
        public static final String CLOSED_DIV = "/div";
        private final HtmlWriter html;

        public ReplaceDefaultParagraphs(HtmlNodeRendererContext context) {
            super(context);
            this.html = context.getWriter();
        }

        @Override
        public void visit(Paragraph paragraph) {
            boolean inTightList = isInTightList(paragraph);
            if (!inTightList) {
                html.tag(OPENED_DIV, getAttrs(paragraph, OPENED_DIV));
            }
            visitChildren(paragraph);
            if (!inTightList) {
                html.tag(CLOSED_DIV);
            }
        }

        private boolean isInTightList(Paragraph paragraph) {
            Node parent = paragraph.getParent();
            if (parent != null) {
                Node gramps = parent.getParent();
                if (gramps != null && gramps instanceof ListBlock) {
                    ListBlock list = (ListBlock) gramps;
                    return list.isTight();
                }
            }
            return false;
        }

        private Map<String, String> getAttrs(Node node, String tagName) {
            return getAttrs(node, tagName, Collections.emptyMap());
        }

        private Map<String, String> getAttrs(Node node, String tagName, Map<String, String> defaultAttributes) {
            return context.extendAttributes(node, tagName, defaultAttributes);
        }
    }

**Comment by robinst** [comment]
Yeah, that's what the API is for now.

I'm not sure about adding options that are very specific (such as "what tag should be used to render paragraphs" and "should a newline be added around paragraphs"). The combination of such options can become very difficult to understand. I'll close this for now, but thanks for the feedback.
