### ISSUE TITLE
No escaping in code block

### ISSUE THREAD

**Issue by yathit** [atlassian/commonmark-java#87]
In coding block, we do not want to escape html. For example

    `$x => array();`

produce 

    $x =&gt; array();

here, we do not want to replace > with `&gt;`

**Comment by robinst** [comment]
Can you explain why? That would mean you could have a code span like this:

````
`<script>alert("Hi");</script>`
````

And when you load that the JS in there is executed (see [XSS](https://en.wikipedia.org/wiki/Cross-site_scripting)).

**Comment by yathit** [comment]
So that coding block can write something like this

![screen shot 2017-07-18 at 10 45 16 am](https://user-images.githubusercontent.com/2137932/28298534-5b5c778a-6ba6-11e7-81ea-da7e8d33aa15.png)

without, of course, executing script.

It is not possible with commonmark-java, but why it is possible in github here?

**Comment by yathit** [comment]
I am sorry. My code have double escape before and in markdown. After remove pre-escape, it works as intended.

**Comment by robinst** [comment]
No worries, thanks for letting me know :).
