### ISSUE TITLE
How to parse multiline cell content?

### ISSUE THREAD

**Issue by jnemecz** [atlassian/commonmark-java#88]
Hello, I need to parse table cells that contain multiline content.

I have an idea for workaround to parse out all cells content, render it as HTML (remove new lines) append bach to parsed document and render it one more time. 

But it is not very clear. Do you have a recommendation hot to solve this?

**Comment by robinst** [comment]
I'm not sure what you mean. Can you please give an example source snippet and the expected rendering you'd like to achieve?
