### ISSUE TITLE
How do I change a double newline into a paragraph and a single newline into a <br/>?

### ISSUE THREAD

**Issue by sandeep-datta** [atlassian/commonmark-java#89]
See title.

**Comment by robinst** [comment]
Double newlines are already turned into paragraphs.

A single newline is called a soft line break in CommonMark. You can configure it using the [`softbreak` method on `HtmlRenderer.Builder`](http://static.javadoc.io/com.atlassian.commonmark/commonmark/0.9.0/org/commonmark/renderer/html/HtmlRenderer.Builder.html#softbreak-java.lang.String-) like so:

```java
HtmlRenderer renderer = HtmlRenderer.builder()
        .softbreak("<br/>")
        .build();
```

Does that answer your question?

**Comment by sandeep-datta** [comment]
Yes this is what I was looking for. Thanks!

**Comment by anandchakru** [comment]
can this `renderer` be initialized once and reused until the life of the server ?

**Comment by robinst** [comment]
@anandchakru Yes, and it's thread-safe as well (for each time you call `render`, there's a separate set of state that is kept only for that render call).

**Comment by DanielGGordon** [comment]
Oh man this was import for an html noob like me. I feel like this should be in the main readme. Spent a long time trying to get the html the way I wanted it.
